### ISSUE TITLE
cli dev 'concurrently' is not recognized (on windows)

### ISSUE THREAD

**Issue by joshball** [atomicobject/ts-react-graphql-starter-kit#5]
Hi,
I am trying to get your starter kit running on windows 10 (node v8.11.2, npm 5.6.0) . 
Looks like there is some issue in your custom `@atomic-object/tscli` code? 

`concurrently` is installed locally and globally. Not sure exactly what is going on, and I can look into it later, but if you happen to know off hand, let me know.

Thanks

```
# yarn dev
yarn run v1.7.0
$ cli dev
'concurrently' is not recognized as an internal or external command,
operable program or batch file.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn concurrently -p name --color -c "red,green,yellow,blue" -n "dev:server:webpack,dev:server:nodemon,dev:client,dev:graphql" 'webpack --config webpack/server.config.js --watch' 'nodemon --watch dist/server.js -- --inspect=9229 dist/server.js' 'node -e '\''require("./webpack/webpack-dev-server").startDevServer()'\' 'sleep 8 && nodemon -e graphql,gql -w modules/ -x '\''cli build:graphql'\' ENOENT
    at notFoundError (w:\src\graphql\ts-react-graphql-starter-kit\node_modules\@atomic-object\tscli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (w:\src\graphql\ts-react-graphql-starter-kit\node_modules\@atomic-object\tscli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (w:\src\graphql\ts-react-graphql-starter-kit\node_modules\@atomic-object\tscli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by atluriajith** [comment]
Did you fix this issue?

**Comment by joshball** [comment]
Sorry @atluriajith, that was a bit ago. I don't even recall anymore. But thanks for asking.
